"""empty message

Revision ID: 0eeaf343b778
Revises: 212e4f73ea3c
Create Date: 2024-09-20 01:08:06.917075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eeaf343b778'
down_revision = '212e4f73ea3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(length=120),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
