"""empty message

Revision ID: 212e4f73ea3c
Revises: c86cbfd7a092
Create Date: 2024-09-20 00:42:19.090343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212e4f73ea3c'
down_revision = 'c86cbfd7a092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bloodType')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('phone')
        batch_op.drop_column('allergies')
        batch_op.drop_column('emergencyContact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergencyContact', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bloodType', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
