"""empty message

Revision ID: 68f6b2ea942a
Revises: b68759214299
Create Date: 2024-09-23 19:40:25.354286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f6b2ea942a'
down_revision = 'b68759214299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=120), nullable=True))
        batch_op.drop_column('emergencyContact')
        batch_op.drop_column('bloodType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloodType', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergencyContact', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('blood_type')
        batch_op.drop_column('emergency_contact')

    # ### end Alembic commands ###
