"""empty message

Revision ID: b68759214299
Revises: de68803a3840
Create Date: 2024-09-23 17:45:26.939017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68759214299'
down_revision = 'de68803a3840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('emergencyContact', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bloodType', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_current')
        batch_op.drop_column('is_active')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('bloodType')
        batch_op.drop_column('allergies')
        batch_op.drop_column('emergencyContact')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
