"""empty message

Revision ID: d972e06b5cb5
Revises: 5aa899e2952c
Create Date: 2024-08-17 00:41:36.632628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd972e06b5cb5'
down_revision = '5aa899e2952c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request_caregiver', schema=None) as batch_op:
        batch_op.drop_column('response_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request_caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
